
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Tenant` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Tenant
 * 
 */
export type TenantModel = runtime.Types.Result.DefaultSelection<Prisma.$TenantPayload>

export type AggregateTenant = {
  _count: TenantCountAggregateOutputType | null
  _min: TenantMinAggregateOutputType | null
  _max: TenantMaxAggregateOutputType | null
}

export type TenantMinAggregateOutputType = {
  id: string | null
  email: string | null
  password: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TenantMaxAggregateOutputType = {
  id: string | null
  email: string | null
  password: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TenantCountAggregateOutputType = {
  id: number
  email: number
  password: number
  name: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TenantMinAggregateInputType = {
  id?: true
  email?: true
  password?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type TenantMaxAggregateInputType = {
  id?: true
  email?: true
  password?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type TenantCountAggregateInputType = {
  id?: true
  email?: true
  password?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TenantAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tenant to aggregate.
   */
  where?: Prisma.TenantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tenants to fetch.
   */
  orderBy?: Prisma.TenantOrderByWithRelationInput | Prisma.TenantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TenantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tenants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tenants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Tenants
  **/
  _count?: true | TenantCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TenantMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TenantMaxAggregateInputType
}

export type GetTenantAggregateType<T extends TenantAggregateArgs> = {
      [P in keyof T & keyof AggregateTenant]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTenant[P]>
    : Prisma.GetScalarType<T[P], AggregateTenant[P]>
}




export type TenantGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TenantWhereInput
  orderBy?: Prisma.TenantOrderByWithAggregationInput | Prisma.TenantOrderByWithAggregationInput[]
  by: Prisma.TenantScalarFieldEnum[] | Prisma.TenantScalarFieldEnum
  having?: Prisma.TenantScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TenantCountAggregateInputType | true
  _min?: TenantMinAggregateInputType
  _max?: TenantMaxAggregateInputType
}

export type TenantGroupByOutputType = {
  id: string
  email: string
  password: string
  name: string
  createdAt: Date
  updatedAt: Date
  _count: TenantCountAggregateOutputType | null
  _min: TenantMinAggregateOutputType | null
  _max: TenantMaxAggregateOutputType | null
}

export type GetTenantGroupByPayload<T extends TenantGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TenantGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TenantGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TenantGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TenantGroupByOutputType[P]>
      }
    >
  >



export type TenantWhereInput = {
  AND?: Prisma.TenantWhereInput | Prisma.TenantWhereInput[]
  OR?: Prisma.TenantWhereInput[]
  NOT?: Prisma.TenantWhereInput | Prisma.TenantWhereInput[]
  id?: Prisma.StringFilter<"Tenant"> | string
  email?: Prisma.StringFilter<"Tenant"> | string
  password?: Prisma.StringFilter<"Tenant"> | string
  name?: Prisma.StringFilter<"Tenant"> | string
  createdAt?: Prisma.DateTimeFilter<"Tenant"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Tenant"> | Date | string
  offers?: Prisma.OfferListRelationFilter
  affiliates?: Prisma.AffiliateListRelationFilter
  clicks?: Prisma.ClickListRelationFilter
  conversions?: Prisma.ConversionListRelationFilter
}

export type TenantOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  offers?: Prisma.OfferOrderByRelationAggregateInput
  affiliates?: Prisma.AffiliateOrderByRelationAggregateInput
  clicks?: Prisma.ClickOrderByRelationAggregateInput
  conversions?: Prisma.ConversionOrderByRelationAggregateInput
}

export type TenantWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  AND?: Prisma.TenantWhereInput | Prisma.TenantWhereInput[]
  OR?: Prisma.TenantWhereInput[]
  NOT?: Prisma.TenantWhereInput | Prisma.TenantWhereInput[]
  password?: Prisma.StringFilter<"Tenant"> | string
  name?: Prisma.StringFilter<"Tenant"> | string
  createdAt?: Prisma.DateTimeFilter<"Tenant"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Tenant"> | Date | string
  offers?: Prisma.OfferListRelationFilter
  affiliates?: Prisma.AffiliateListRelationFilter
  clicks?: Prisma.ClickListRelationFilter
  conversions?: Prisma.ConversionListRelationFilter
}, "id" | "email">

export type TenantOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TenantCountOrderByAggregateInput
  _max?: Prisma.TenantMaxOrderByAggregateInput
  _min?: Prisma.TenantMinOrderByAggregateInput
}

export type TenantScalarWhereWithAggregatesInput = {
  AND?: Prisma.TenantScalarWhereWithAggregatesInput | Prisma.TenantScalarWhereWithAggregatesInput[]
  OR?: Prisma.TenantScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TenantScalarWhereWithAggregatesInput | Prisma.TenantScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Tenant"> | string
  email?: Prisma.StringWithAggregatesFilter<"Tenant"> | string
  password?: Prisma.StringWithAggregatesFilter<"Tenant"> | string
  name?: Prisma.StringWithAggregatesFilter<"Tenant"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Tenant"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Tenant"> | Date | string
}

export type TenantCreateInput = {
  id?: string
  email: string
  password: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  offers?: Prisma.OfferCreateNestedManyWithoutTenantInput
  affiliates?: Prisma.AffiliateCreateNestedManyWithoutTenantInput
  clicks?: Prisma.ClickCreateNestedManyWithoutTenantInput
  conversions?: Prisma.ConversionCreateNestedManyWithoutTenantInput
}

export type TenantUncheckedCreateInput = {
  id?: string
  email: string
  password: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  offers?: Prisma.OfferUncheckedCreateNestedManyWithoutTenantInput
  affiliates?: Prisma.AffiliateUncheckedCreateNestedManyWithoutTenantInput
  clicks?: Prisma.ClickUncheckedCreateNestedManyWithoutTenantInput
  conversions?: Prisma.ConversionUncheckedCreateNestedManyWithoutTenantInput
}

export type TenantUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  offers?: Prisma.OfferUpdateManyWithoutTenantNestedInput
  affiliates?: Prisma.AffiliateUpdateManyWithoutTenantNestedInput
  clicks?: Prisma.ClickUpdateManyWithoutTenantNestedInput
  conversions?: Prisma.ConversionUpdateManyWithoutTenantNestedInput
}

export type TenantUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  offers?: Prisma.OfferUncheckedUpdateManyWithoutTenantNestedInput
  affiliates?: Prisma.AffiliateUncheckedUpdateManyWithoutTenantNestedInput
  clicks?: Prisma.ClickUncheckedUpdateManyWithoutTenantNestedInput
  conversions?: Prisma.ConversionUncheckedUpdateManyWithoutTenantNestedInput
}

export type TenantCreateManyInput = {
  id?: string
  email: string
  password: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TenantUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TenantUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TenantCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TenantMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TenantMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TenantScalarRelationFilter = {
  is?: Prisma.TenantWhereInput
  isNot?: Prisma.TenantWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type TenantCreateNestedOneWithoutOffersInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutOffersInput, Prisma.TenantUncheckedCreateWithoutOffersInput>
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutOffersInput
  connect?: Prisma.TenantWhereUniqueInput
}

export type TenantUpdateOneRequiredWithoutOffersNestedInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutOffersInput, Prisma.TenantUncheckedCreateWithoutOffersInput>
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutOffersInput
  upsert?: Prisma.TenantUpsertWithoutOffersInput
  connect?: Prisma.TenantWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TenantUpdateToOneWithWhereWithoutOffersInput, Prisma.TenantUpdateWithoutOffersInput>, Prisma.TenantUncheckedUpdateWithoutOffersInput>
}

export type TenantCreateNestedOneWithoutAffiliatesInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutAffiliatesInput, Prisma.TenantUncheckedCreateWithoutAffiliatesInput>
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutAffiliatesInput
  connect?: Prisma.TenantWhereUniqueInput
}

export type TenantUpdateOneRequiredWithoutAffiliatesNestedInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutAffiliatesInput, Prisma.TenantUncheckedCreateWithoutAffiliatesInput>
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutAffiliatesInput
  upsert?: Prisma.TenantUpsertWithoutAffiliatesInput
  connect?: Prisma.TenantWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TenantUpdateToOneWithWhereWithoutAffiliatesInput, Prisma.TenantUpdateWithoutAffiliatesInput>, Prisma.TenantUncheckedUpdateWithoutAffiliatesInput>
}

export type TenantCreateNestedOneWithoutClicksInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutClicksInput, Prisma.TenantUncheckedCreateWithoutClicksInput>
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutClicksInput
  connect?: Prisma.TenantWhereUniqueInput
}

export type TenantUpdateOneRequiredWithoutClicksNestedInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutClicksInput, Prisma.TenantUncheckedCreateWithoutClicksInput>
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutClicksInput
  upsert?: Prisma.TenantUpsertWithoutClicksInput
  connect?: Prisma.TenantWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TenantUpdateToOneWithWhereWithoutClicksInput, Prisma.TenantUpdateWithoutClicksInput>, Prisma.TenantUncheckedUpdateWithoutClicksInput>
}

export type TenantCreateNestedOneWithoutConversionsInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutConversionsInput, Prisma.TenantUncheckedCreateWithoutConversionsInput>
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutConversionsInput
  connect?: Prisma.TenantWhereUniqueInput
}

export type TenantUpdateOneRequiredWithoutConversionsNestedInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutConversionsInput, Prisma.TenantUncheckedCreateWithoutConversionsInput>
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutConversionsInput
  upsert?: Prisma.TenantUpsertWithoutConversionsInput
  connect?: Prisma.TenantWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TenantUpdateToOneWithWhereWithoutConversionsInput, Prisma.TenantUpdateWithoutConversionsInput>, Prisma.TenantUncheckedUpdateWithoutConversionsInput>
}

export type TenantCreateWithoutOffersInput = {
  id?: string
  email: string
  password: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  affiliates?: Prisma.AffiliateCreateNestedManyWithoutTenantInput
  clicks?: Prisma.ClickCreateNestedManyWithoutTenantInput
  conversions?: Prisma.ConversionCreateNestedManyWithoutTenantInput
}

export type TenantUncheckedCreateWithoutOffersInput = {
  id?: string
  email: string
  password: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  affiliates?: Prisma.AffiliateUncheckedCreateNestedManyWithoutTenantInput
  clicks?: Prisma.ClickUncheckedCreateNestedManyWithoutTenantInput
  conversions?: Prisma.ConversionUncheckedCreateNestedManyWithoutTenantInput
}

export type TenantCreateOrConnectWithoutOffersInput = {
  where: Prisma.TenantWhereUniqueInput
  create: Prisma.XOR<Prisma.TenantCreateWithoutOffersInput, Prisma.TenantUncheckedCreateWithoutOffersInput>
}

export type TenantUpsertWithoutOffersInput = {
  update: Prisma.XOR<Prisma.TenantUpdateWithoutOffersInput, Prisma.TenantUncheckedUpdateWithoutOffersInput>
  create: Prisma.XOR<Prisma.TenantCreateWithoutOffersInput, Prisma.TenantUncheckedCreateWithoutOffersInput>
  where?: Prisma.TenantWhereInput
}

export type TenantUpdateToOneWithWhereWithoutOffersInput = {
  where?: Prisma.TenantWhereInput
  data: Prisma.XOR<Prisma.TenantUpdateWithoutOffersInput, Prisma.TenantUncheckedUpdateWithoutOffersInput>
}

export type TenantUpdateWithoutOffersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  affiliates?: Prisma.AffiliateUpdateManyWithoutTenantNestedInput
  clicks?: Prisma.ClickUpdateManyWithoutTenantNestedInput
  conversions?: Prisma.ConversionUpdateManyWithoutTenantNestedInput
}

export type TenantUncheckedUpdateWithoutOffersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  affiliates?: Prisma.AffiliateUncheckedUpdateManyWithoutTenantNestedInput
  clicks?: Prisma.ClickUncheckedUpdateManyWithoutTenantNestedInput
  conversions?: Prisma.ConversionUncheckedUpdateManyWithoutTenantNestedInput
}

export type TenantCreateWithoutAffiliatesInput = {
  id?: string
  email: string
  password: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  offers?: Prisma.OfferCreateNestedManyWithoutTenantInput
  clicks?: Prisma.ClickCreateNestedManyWithoutTenantInput
  conversions?: Prisma.ConversionCreateNestedManyWithoutTenantInput
}

export type TenantUncheckedCreateWithoutAffiliatesInput = {
  id?: string
  email: string
  password: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  offers?: Prisma.OfferUncheckedCreateNestedManyWithoutTenantInput
  clicks?: Prisma.ClickUncheckedCreateNestedManyWithoutTenantInput
  conversions?: Prisma.ConversionUncheckedCreateNestedManyWithoutTenantInput
}

export type TenantCreateOrConnectWithoutAffiliatesInput = {
  where: Prisma.TenantWhereUniqueInput
  create: Prisma.XOR<Prisma.TenantCreateWithoutAffiliatesInput, Prisma.TenantUncheckedCreateWithoutAffiliatesInput>
}

export type TenantUpsertWithoutAffiliatesInput = {
  update: Prisma.XOR<Prisma.TenantUpdateWithoutAffiliatesInput, Prisma.TenantUncheckedUpdateWithoutAffiliatesInput>
  create: Prisma.XOR<Prisma.TenantCreateWithoutAffiliatesInput, Prisma.TenantUncheckedCreateWithoutAffiliatesInput>
  where?: Prisma.TenantWhereInput
}

export type TenantUpdateToOneWithWhereWithoutAffiliatesInput = {
  where?: Prisma.TenantWhereInput
  data: Prisma.XOR<Prisma.TenantUpdateWithoutAffiliatesInput, Prisma.TenantUncheckedUpdateWithoutAffiliatesInput>
}

export type TenantUpdateWithoutAffiliatesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  offers?: Prisma.OfferUpdateManyWithoutTenantNestedInput
  clicks?: Prisma.ClickUpdateManyWithoutTenantNestedInput
  conversions?: Prisma.ConversionUpdateManyWithoutTenantNestedInput
}

export type TenantUncheckedUpdateWithoutAffiliatesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  offers?: Prisma.OfferUncheckedUpdateManyWithoutTenantNestedInput
  clicks?: Prisma.ClickUncheckedUpdateManyWithoutTenantNestedInput
  conversions?: Prisma.ConversionUncheckedUpdateManyWithoutTenantNestedInput
}

export type TenantCreateWithoutClicksInput = {
  id?: string
  email: string
  password: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  offers?: Prisma.OfferCreateNestedManyWithoutTenantInput
  affiliates?: Prisma.AffiliateCreateNestedManyWithoutTenantInput
  conversions?: Prisma.ConversionCreateNestedManyWithoutTenantInput
}

export type TenantUncheckedCreateWithoutClicksInput = {
  id?: string
  email: string
  password: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  offers?: Prisma.OfferUncheckedCreateNestedManyWithoutTenantInput
  affiliates?: Prisma.AffiliateUncheckedCreateNestedManyWithoutTenantInput
  conversions?: Prisma.ConversionUncheckedCreateNestedManyWithoutTenantInput
}

export type TenantCreateOrConnectWithoutClicksInput = {
  where: Prisma.TenantWhereUniqueInput
  create: Prisma.XOR<Prisma.TenantCreateWithoutClicksInput, Prisma.TenantUncheckedCreateWithoutClicksInput>
}

export type TenantUpsertWithoutClicksInput = {
  update: Prisma.XOR<Prisma.TenantUpdateWithoutClicksInput, Prisma.TenantUncheckedUpdateWithoutClicksInput>
  create: Prisma.XOR<Prisma.TenantCreateWithoutClicksInput, Prisma.TenantUncheckedCreateWithoutClicksInput>
  where?: Prisma.TenantWhereInput
}

export type TenantUpdateToOneWithWhereWithoutClicksInput = {
  where?: Prisma.TenantWhereInput
  data: Prisma.XOR<Prisma.TenantUpdateWithoutClicksInput, Prisma.TenantUncheckedUpdateWithoutClicksInput>
}

export type TenantUpdateWithoutClicksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  offers?: Prisma.OfferUpdateManyWithoutTenantNestedInput
  affiliates?: Prisma.AffiliateUpdateManyWithoutTenantNestedInput
  conversions?: Prisma.ConversionUpdateManyWithoutTenantNestedInput
}

export type TenantUncheckedUpdateWithoutClicksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  offers?: Prisma.OfferUncheckedUpdateManyWithoutTenantNestedInput
  affiliates?: Prisma.AffiliateUncheckedUpdateManyWithoutTenantNestedInput
  conversions?: Prisma.ConversionUncheckedUpdateManyWithoutTenantNestedInput
}

export type TenantCreateWithoutConversionsInput = {
  id?: string
  email: string
  password: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  offers?: Prisma.OfferCreateNestedManyWithoutTenantInput
  affiliates?: Prisma.AffiliateCreateNestedManyWithoutTenantInput
  clicks?: Prisma.ClickCreateNestedManyWithoutTenantInput
}

export type TenantUncheckedCreateWithoutConversionsInput = {
  id?: string
  email: string
  password: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  offers?: Prisma.OfferUncheckedCreateNestedManyWithoutTenantInput
  affiliates?: Prisma.AffiliateUncheckedCreateNestedManyWithoutTenantInput
  clicks?: Prisma.ClickUncheckedCreateNestedManyWithoutTenantInput
}

export type TenantCreateOrConnectWithoutConversionsInput = {
  where: Prisma.TenantWhereUniqueInput
  create: Prisma.XOR<Prisma.TenantCreateWithoutConversionsInput, Prisma.TenantUncheckedCreateWithoutConversionsInput>
}

export type TenantUpsertWithoutConversionsInput = {
  update: Prisma.XOR<Prisma.TenantUpdateWithoutConversionsInput, Prisma.TenantUncheckedUpdateWithoutConversionsInput>
  create: Prisma.XOR<Prisma.TenantCreateWithoutConversionsInput, Prisma.TenantUncheckedCreateWithoutConversionsInput>
  where?: Prisma.TenantWhereInput
}

export type TenantUpdateToOneWithWhereWithoutConversionsInput = {
  where?: Prisma.TenantWhereInput
  data: Prisma.XOR<Prisma.TenantUpdateWithoutConversionsInput, Prisma.TenantUncheckedUpdateWithoutConversionsInput>
}

export type TenantUpdateWithoutConversionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  offers?: Prisma.OfferUpdateManyWithoutTenantNestedInput
  affiliates?: Prisma.AffiliateUpdateManyWithoutTenantNestedInput
  clicks?: Prisma.ClickUpdateManyWithoutTenantNestedInput
}

export type TenantUncheckedUpdateWithoutConversionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  offers?: Prisma.OfferUncheckedUpdateManyWithoutTenantNestedInput
  affiliates?: Prisma.AffiliateUncheckedUpdateManyWithoutTenantNestedInput
  clicks?: Prisma.ClickUncheckedUpdateManyWithoutTenantNestedInput
}


/**
 * Count Type TenantCountOutputType
 */

export type TenantCountOutputType = {
  offers: number
  affiliates: number
  clicks: number
  conversions: number
}

export type TenantCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  offers?: boolean | TenantCountOutputTypeCountOffersArgs
  affiliates?: boolean | TenantCountOutputTypeCountAffiliatesArgs
  clicks?: boolean | TenantCountOutputTypeCountClicksArgs
  conversions?: boolean | TenantCountOutputTypeCountConversionsArgs
}

/**
 * TenantCountOutputType without action
 */
export type TenantCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TenantCountOutputType
   */
  select?: Prisma.TenantCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TenantCountOutputType without action
 */
export type TenantCountOutputTypeCountOffersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OfferWhereInput
}

/**
 * TenantCountOutputType without action
 */
export type TenantCountOutputTypeCountAffiliatesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AffiliateWhereInput
}

/**
 * TenantCountOutputType without action
 */
export type TenantCountOutputTypeCountClicksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClickWhereInput
}

/**
 * TenantCountOutputType without action
 */
export type TenantCountOutputTypeCountConversionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ConversionWhereInput
}


export type TenantSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  password?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  offers?: boolean | Prisma.Tenant$offersArgs<ExtArgs>
  affiliates?: boolean | Prisma.Tenant$affiliatesArgs<ExtArgs>
  clicks?: boolean | Prisma.Tenant$clicksArgs<ExtArgs>
  conversions?: boolean | Prisma.Tenant$conversionsArgs<ExtArgs>
  _count?: boolean | Prisma.TenantCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tenant"]>

export type TenantSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  password?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["tenant"]>

export type TenantSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  password?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["tenant"]>

export type TenantSelectScalar = {
  id?: boolean
  email?: boolean
  password?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TenantOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "email" | "password" | "name" | "createdAt" | "updatedAt", ExtArgs["result"]["tenant"]>
export type TenantInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  offers?: boolean | Prisma.Tenant$offersArgs<ExtArgs>
  affiliates?: boolean | Prisma.Tenant$affiliatesArgs<ExtArgs>
  clicks?: boolean | Prisma.Tenant$clicksArgs<ExtArgs>
  conversions?: boolean | Prisma.Tenant$conversionsArgs<ExtArgs>
  _count?: boolean | Prisma.TenantCountOutputTypeDefaultArgs<ExtArgs>
}
export type TenantIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type TenantIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $TenantPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Tenant"
  objects: {
    offers: Prisma.$OfferPayload<ExtArgs>[]
    affiliates: Prisma.$AffiliatePayload<ExtArgs>[]
    clicks: Prisma.$ClickPayload<ExtArgs>[]
    conversions: Prisma.$ConversionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    email: string
    password: string
    name: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["tenant"]>
  composites: {}
}

export type TenantGetPayload<S extends boolean | null | undefined | TenantDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TenantPayload, S>

export type TenantCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TenantFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TenantCountAggregateInputType | true
  }

export interface TenantDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Tenant'], meta: { name: 'Tenant' } }
  /**
   * Find zero or one Tenant that matches the filter.
   * @param {TenantFindUniqueArgs} args - Arguments to find a Tenant
   * @example
   * // Get one Tenant
   * const tenant = await prisma.tenant.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TenantFindUniqueArgs>(args: Prisma.SelectSubset<T, TenantFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Tenant that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TenantFindUniqueOrThrowArgs} args - Arguments to find a Tenant
   * @example
   * // Get one Tenant
   * const tenant = await prisma.tenant.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TenantFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TenantFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tenant that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantFindFirstArgs} args - Arguments to find a Tenant
   * @example
   * // Get one Tenant
   * const tenant = await prisma.tenant.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TenantFindFirstArgs>(args?: Prisma.SelectSubset<T, TenantFindFirstArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tenant that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantFindFirstOrThrowArgs} args - Arguments to find a Tenant
   * @example
   * // Get one Tenant
   * const tenant = await prisma.tenant.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TenantFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TenantFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tenants that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tenants
   * const tenants = await prisma.tenant.findMany()
   * 
   * // Get first 10 Tenants
   * const tenants = await prisma.tenant.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tenantWithIdOnly = await prisma.tenant.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TenantFindManyArgs>(args?: Prisma.SelectSubset<T, TenantFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Tenant.
   * @param {TenantCreateArgs} args - Arguments to create a Tenant.
   * @example
   * // Create one Tenant
   * const Tenant = await prisma.tenant.create({
   *   data: {
   *     // ... data to create a Tenant
   *   }
   * })
   * 
   */
  create<T extends TenantCreateArgs>(args: Prisma.SelectSubset<T, TenantCreateArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tenants.
   * @param {TenantCreateManyArgs} args - Arguments to create many Tenants.
   * @example
   * // Create many Tenants
   * const tenant = await prisma.tenant.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TenantCreateManyArgs>(args?: Prisma.SelectSubset<T, TenantCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tenants and returns the data saved in the database.
   * @param {TenantCreateManyAndReturnArgs} args - Arguments to create many Tenants.
   * @example
   * // Create many Tenants
   * const tenant = await prisma.tenant.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tenants and only return the `id`
   * const tenantWithIdOnly = await prisma.tenant.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TenantCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TenantCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Tenant.
   * @param {TenantDeleteArgs} args - Arguments to delete one Tenant.
   * @example
   * // Delete one Tenant
   * const Tenant = await prisma.tenant.delete({
   *   where: {
   *     // ... filter to delete one Tenant
   *   }
   * })
   * 
   */
  delete<T extends TenantDeleteArgs>(args: Prisma.SelectSubset<T, TenantDeleteArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Tenant.
   * @param {TenantUpdateArgs} args - Arguments to update one Tenant.
   * @example
   * // Update one Tenant
   * const tenant = await prisma.tenant.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TenantUpdateArgs>(args: Prisma.SelectSubset<T, TenantUpdateArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tenants.
   * @param {TenantDeleteManyArgs} args - Arguments to filter Tenants to delete.
   * @example
   * // Delete a few Tenants
   * const { count } = await prisma.tenant.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TenantDeleteManyArgs>(args?: Prisma.SelectSubset<T, TenantDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tenants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tenants
   * const tenant = await prisma.tenant.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TenantUpdateManyArgs>(args: Prisma.SelectSubset<T, TenantUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tenants and returns the data updated in the database.
   * @param {TenantUpdateManyAndReturnArgs} args - Arguments to update many Tenants.
   * @example
   * // Update many Tenants
   * const tenant = await prisma.tenant.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tenants and only return the `id`
   * const tenantWithIdOnly = await prisma.tenant.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TenantUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TenantUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Tenant.
   * @param {TenantUpsertArgs} args - Arguments to update or create a Tenant.
   * @example
   * // Update or create a Tenant
   * const tenant = await prisma.tenant.upsert({
   *   create: {
   *     // ... data to create a Tenant
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Tenant we want to update
   *   }
   * })
   */
  upsert<T extends TenantUpsertArgs>(args: Prisma.SelectSubset<T, TenantUpsertArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tenants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantCountArgs} args - Arguments to filter Tenants to count.
   * @example
   * // Count the number of Tenants
   * const count = await prisma.tenant.count({
   *   where: {
   *     // ... the filter for the Tenants we want to count
   *   }
   * })
  **/
  count<T extends TenantCountArgs>(
    args?: Prisma.Subset<T, TenantCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TenantCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Tenant.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TenantAggregateArgs>(args: Prisma.Subset<T, TenantAggregateArgs>): Prisma.PrismaPromise<GetTenantAggregateType<T>>

  /**
   * Group by Tenant.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TenantGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TenantGroupByArgs['orderBy'] }
      : { orderBy?: TenantGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TenantGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTenantGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Tenant model
 */
readonly fields: TenantFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Tenant.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TenantClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  offers<T extends Prisma.Tenant$offersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tenant$offersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfferPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  affiliates<T extends Prisma.Tenant$affiliatesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tenant$affiliatesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AffiliatePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  clicks<T extends Prisma.Tenant$clicksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tenant$clicksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClickPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  conversions<T extends Prisma.Tenant$conversionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tenant$conversionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConversionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Tenant model
 */
export interface TenantFieldRefs {
  readonly id: Prisma.FieldRef<"Tenant", 'String'>
  readonly email: Prisma.FieldRef<"Tenant", 'String'>
  readonly password: Prisma.FieldRef<"Tenant", 'String'>
  readonly name: Prisma.FieldRef<"Tenant", 'String'>
  readonly createdAt: Prisma.FieldRef<"Tenant", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Tenant", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Tenant findUnique
 */
export type TenantFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  /**
   * Filter, which Tenant to fetch.
   */
  where: Prisma.TenantWhereUniqueInput
}

/**
 * Tenant findUniqueOrThrow
 */
export type TenantFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  /**
   * Filter, which Tenant to fetch.
   */
  where: Prisma.TenantWhereUniqueInput
}

/**
 * Tenant findFirst
 */
export type TenantFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  /**
   * Filter, which Tenant to fetch.
   */
  where?: Prisma.TenantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tenants to fetch.
   */
  orderBy?: Prisma.TenantOrderByWithRelationInput | Prisma.TenantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tenants.
   */
  cursor?: Prisma.TenantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tenants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tenants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tenants.
   */
  distinct?: Prisma.TenantScalarFieldEnum | Prisma.TenantScalarFieldEnum[]
}

/**
 * Tenant findFirstOrThrow
 */
export type TenantFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  /**
   * Filter, which Tenant to fetch.
   */
  where?: Prisma.TenantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tenants to fetch.
   */
  orderBy?: Prisma.TenantOrderByWithRelationInput | Prisma.TenantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tenants.
   */
  cursor?: Prisma.TenantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tenants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tenants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tenants.
   */
  distinct?: Prisma.TenantScalarFieldEnum | Prisma.TenantScalarFieldEnum[]
}

/**
 * Tenant findMany
 */
export type TenantFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  /**
   * Filter, which Tenants to fetch.
   */
  where?: Prisma.TenantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tenants to fetch.
   */
  orderBy?: Prisma.TenantOrderByWithRelationInput | Prisma.TenantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Tenants.
   */
  cursor?: Prisma.TenantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tenants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tenants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tenants.
   */
  distinct?: Prisma.TenantScalarFieldEnum | Prisma.TenantScalarFieldEnum[]
}

/**
 * Tenant create
 */
export type TenantCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  /**
   * The data needed to create a Tenant.
   */
  data: Prisma.XOR<Prisma.TenantCreateInput, Prisma.TenantUncheckedCreateInput>
}

/**
 * Tenant createMany
 */
export type TenantCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Tenants.
   */
  data: Prisma.TenantCreateManyInput | Prisma.TenantCreateManyInput[]
}

/**
 * Tenant createManyAndReturn
 */
export type TenantCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * The data used to create many Tenants.
   */
  data: Prisma.TenantCreateManyInput | Prisma.TenantCreateManyInput[]
}

/**
 * Tenant update
 */
export type TenantUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  /**
   * The data needed to update a Tenant.
   */
  data: Prisma.XOR<Prisma.TenantUpdateInput, Prisma.TenantUncheckedUpdateInput>
  /**
   * Choose, which Tenant to update.
   */
  where: Prisma.TenantWhereUniqueInput
}

/**
 * Tenant updateMany
 */
export type TenantUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Tenants.
   */
  data: Prisma.XOR<Prisma.TenantUpdateManyMutationInput, Prisma.TenantUncheckedUpdateManyInput>
  /**
   * Filter which Tenants to update
   */
  where?: Prisma.TenantWhereInput
  /**
   * Limit how many Tenants to update.
   */
  limit?: number
}

/**
 * Tenant updateManyAndReturn
 */
export type TenantUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * The data used to update Tenants.
   */
  data: Prisma.XOR<Prisma.TenantUpdateManyMutationInput, Prisma.TenantUncheckedUpdateManyInput>
  /**
   * Filter which Tenants to update
   */
  where?: Prisma.TenantWhereInput
  /**
   * Limit how many Tenants to update.
   */
  limit?: number
}

/**
 * Tenant upsert
 */
export type TenantUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  /**
   * The filter to search for the Tenant to update in case it exists.
   */
  where: Prisma.TenantWhereUniqueInput
  /**
   * In case the Tenant found by the `where` argument doesn't exist, create a new Tenant with this data.
   */
  create: Prisma.XOR<Prisma.TenantCreateInput, Prisma.TenantUncheckedCreateInput>
  /**
   * In case the Tenant was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TenantUpdateInput, Prisma.TenantUncheckedUpdateInput>
}

/**
 * Tenant delete
 */
export type TenantDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  /**
   * Filter which Tenant to delete.
   */
  where: Prisma.TenantWhereUniqueInput
}

/**
 * Tenant deleteMany
 */
export type TenantDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tenants to delete
   */
  where?: Prisma.TenantWhereInput
  /**
   * Limit how many Tenants to delete.
   */
  limit?: number
}

/**
 * Tenant.offers
 */
export type Tenant$offersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Offer
   */
  select?: Prisma.OfferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Offer
   */
  omit?: Prisma.OfferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfferInclude<ExtArgs> | null
  where?: Prisma.OfferWhereInput
  orderBy?: Prisma.OfferOrderByWithRelationInput | Prisma.OfferOrderByWithRelationInput[]
  cursor?: Prisma.OfferWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OfferScalarFieldEnum | Prisma.OfferScalarFieldEnum[]
}

/**
 * Tenant.affiliates
 */
export type Tenant$affiliatesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Affiliate
   */
  select?: Prisma.AffiliateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Affiliate
   */
  omit?: Prisma.AffiliateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AffiliateInclude<ExtArgs> | null
  where?: Prisma.AffiliateWhereInput
  orderBy?: Prisma.AffiliateOrderByWithRelationInput | Prisma.AffiliateOrderByWithRelationInput[]
  cursor?: Prisma.AffiliateWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AffiliateScalarFieldEnum | Prisma.AffiliateScalarFieldEnum[]
}

/**
 * Tenant.clicks
 */
export type Tenant$clicksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Click
   */
  select?: Prisma.ClickSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Click
   */
  omit?: Prisma.ClickOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClickInclude<ExtArgs> | null
  where?: Prisma.ClickWhereInput
  orderBy?: Prisma.ClickOrderByWithRelationInput | Prisma.ClickOrderByWithRelationInput[]
  cursor?: Prisma.ClickWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ClickScalarFieldEnum | Prisma.ClickScalarFieldEnum[]
}

/**
 * Tenant.conversions
 */
export type Tenant$conversionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Conversion
   */
  select?: Prisma.ConversionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Conversion
   */
  omit?: Prisma.ConversionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConversionInclude<ExtArgs> | null
  where?: Prisma.ConversionWhereInput
  orderBy?: Prisma.ConversionOrderByWithRelationInput | Prisma.ConversionOrderByWithRelationInput[]
  cursor?: Prisma.ConversionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ConversionScalarFieldEnum | Prisma.ConversionScalarFieldEnum[]
}

/**
 * Tenant without action
 */
export type TenantDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
}
